<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="BoardRepresentation\Board.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BoardRepresentation\**\*.cs" />
    <Compile Remove="ConsoleAppTests\**\*.cs" />
  </ItemGroup>

</Project>
